package es.cga.sbsample.srv.srvclient.service.createclient;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;

import es.cga.sbsample.model.modelsbsample.DtoClient;
import es.cga.sbsample.srv.srvclient.service.createclient.in.Client;

@Mapper(componentModel = "spring")
public interface CreateClientMapper {

	
	/** Example mapping, shows the typical conversion
	 * from front to DB objects.
	 * @param client
	 * @return
	 */
	@Mappings({
		@Mapping(target = "firstname", source = "name"),
		@Mapping(target = "lastname", source = "surname")
		//autogenerated credit mapping
	})
	public DtoClient toDtoClient(Client client);
}
